# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference


# 1: Config file 
# version: 2.1

# # Define a job to be invoked later in a workflow.
# # See: https://circleci.com/docs/2.0/configuration-reference/#jobs
# jobs:
#   say-hello:
#     # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
#     # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
#     docker:
#       - image: cimg/base:stable
#     # Add steps to the job
#     # See: https://circleci.com/docs/2.0/configuration-reference/#steps
#     steps:
#       - checkout
#       - run:
#           name: "Say hello"
#           command: "echo Hello, World!"

#   app-engineer:
#     docker:
#       - image: cimg/base:stable

#     steps:
#       - checkout
#       - run:
#           name: "App engineer"
#           command: "echo Hello, the app engineer!!"

# # Invoke jobs via workflows
# # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
# workflows:
  myworkflows:
    jobs:
      - say-hello
      - app-engineer

# 2: Config file 
version: 2.1
orbs:
  android: circleci/android@2.1.2
  # flutter-orb: circleci/flutter@1.1.0
  # ruby: circleci/ruby@1.8.0
  # macos: circleci/macos@2.3.1
jobs:
  integration_test_android:
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2022.03.1
    steps:
      - checkout
      - flutter-orb/install_sdk_and_pub:
          cache-version: machine
          flutter_version: 2.10.3
      - android/create-avd:
          avd-name: flutter
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: flutter
          post-emulator-launch-assemble-command: 'flutter build apk --debug'
          restore-gradle-cache-find-args: ./android -name 'build.gradle'
      - android/run-tests:
          test-command: flutter drive --target=test_driver/app.dart
      - store_artifacts:
          path: ozzie

  distribute_android:
    executor:
      name: android/android-docker
      resource-class: xlarge
      tag: 2022.03.1
    steps:
      - checkout
      - flutter-orb/install_sdk_and_pub:
          cache-version: docker
          flutter_version: 2.10.3
      - flutter-orb/install_android_gradle
      - ruby/install-deps:
          app-dir: android
          key: android
      - run:
          command: bundle exec fastlane distribute_debug
          working_directory: android

workflows:
  test_and_distribute:
    jobs:
      - flutter-orb/unit_test:
          version: 2.10.3
      - flutter-orb/lint:
          version: 2.10.3
      - integration_test_android
      - distribute_android:
          context: # Context
            - mobile